//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vivienda.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ViviendaEntities : DbContext
    {
        public ViviendaEntities()
            : base("name=ViviendaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Estado> Tbl_Estado { get; set; }
        public virtual DbSet<Tbl_Condominio> Tbl_Condominio { get; set; }
        public virtual DbSet<Tbl_Propietario> Tbl_Propietario { get; set; }
        public virtual DbSet<Tbl_TipoVivienda> Tbl_TipoVivienda { get; set; }
        public virtual DbSet<Tbl_Vivienda> Tbl_Vivienda { get; set; }
    
        public virtual ObjectResult<SP_Condominio_Consulta_Result> SP_Condominio_Consulta(string condominio, Nullable<int> id_Condominio, Nullable<int> activo)
        {
            var condominioParameter = condominio != null ?
                new ObjectParameter("Condominio", condominio) :
                new ObjectParameter("Condominio", typeof(string));
    
            var id_CondominioParameter = id_Condominio.HasValue ?
                new ObjectParameter("Id_Condominio", id_Condominio) :
                new ObjectParameter("Id_Condominio", typeof(int));
    
            var activoParameter = activo.HasValue ?
                new ObjectParameter("Activo", activo) :
                new ObjectParameter("Activo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Condominio_Consulta_Result>("SP_Condominio_Consulta", condominioParameter, id_CondominioParameter, activoParameter);
        }
    }
}
