//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vivienda.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Propietario
    {
        public int Id_Propietario { get; set; }
        public string Nombre { get; set; }
        public string ApePaterno { get; set; }
        public string ApeMaterno { get; set; }
        public string Correo { get; set; }
        public string Tel1 { get; set; }
        public string Tel2 { get; set; }
        public string Cel1 { get; set; }
        public string Cel2 { get; set; }
        public bool Activo { get; set; }
        public int Id_Vivienda { get; set; }
    
        public virtual Tbl_Vivienda Tbl_Vivienda { get; set; }
    }
}
