//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vivienda.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Vivienda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Vivienda()
        {
            this.Tbl_Propietario = new HashSet<Tbl_Propietario>();
        }
    
        public int Id_Vivienda { get; set; }
        public string Vivienda { get; set; }
        public int Id_TipoVivienda { get; set; }
        public string Calle { get; set; }
        public string Lote { get; set; }
        public string NumExt { get; set; }
        public string NumInt { get; set; }
        public int Id_Condominio { get; set; }
        public bool Activo { get; set; }
    
        public virtual Tbl_Condominio Tbl_Condominio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Propietario> Tbl_Propietario { get; set; }
        public virtual Tbl_TipoVivienda Tbl_TipoVivienda { get; set; }
    }
}
