//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vivienda.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_TipoVivienda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_TipoVivienda()
        {
            this.Tbl_Vivienda = new HashSet<Tbl_Vivienda>();
        }
    
        public int Id_TipoVivienda { get; set; }
        public string TipoVivienda { get; set; }
        public string Clave { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Vivienda> Tbl_Vivienda { get; set; }
    }
}
